### ISSUE TITLE
Move to use python logger

### ISSUE THREAD

**Issue by benwoo1110** [benwoo1110/testcase-maker#3]
Currently, all the output uses `print(...)`. I would like to move then to use `logger` class provided by python which can allow for different levels such as DEBUG, INFO etc...

Example of places where print should be replaced:
https://github.com/benwoo1110/testcase-maker/blob/ba1e18bcaa0c2aa11af6f2d37fecb6d2d64120ec/testcase_maker/generator.py#L77

**Comment by gursi26** [comment]
Hi! Please do consider assigning this task to me. I would like to work on it.

**Comment by benwoo1110** [comment]
Sure, assigned to you.
