### ISSUE TITLE
CPP Executor

### ISSUE THREAD

**Issue by benwoo1110** [benwoo1110/testcase-maker#5]
Current the [executor for cpp](https://github.com/benwoo1110/testcase-maker/blob/main/testcase_maker/executors/cpp.py) scripts is not done yet. The main task is for it to run cli commands to compile and execute a cpp code file with stdin. You can see the [java](https://github.com/benwoo1110/testcase-maker/blob/main/testcase_maker/executors/java.py) and [python](https://github.com/benwoo1110/testcase-maker/blob/main/testcase_maker/executors/python.py) executors for example.

**Comment by daksh10110** [comment]
Hey, I think I can do it, can you assign it to me.

**Comment by benwoo1110** [comment]
Sure, looking forward to your PR 😄
