### ISSUE TITLE
Customisable line break options

### ISSUE THREAD

**Issue by benwoo1110** [benwoo1110/testcase-maker#6]
There is generally 3 different newline format depending on which OS and file encoding you are using: CR LF, LFCR line break types. Currently, it's hardcoded to always use LF (i.e. `\n`). I would like a way to customise this, likely by adding an attribute to the TestcaseGenerator class.

The current hard coded way:
https://github.com/benwoo1110/testcase-maker/blob/18105139b71f1ce5775ed49919c54b20d57a0f85/testcase_maker/generator.py#L127

**Comment by MokshitSurana** [comment]
we can use `platform.system()` to check which OS we are using and according to that we can add the 3 different newline format?

**Comment by benwoo1110** [comment]
It is possible to use `platform.system()` as the default, but I will still want to so be customisable as people may deploy the testcases on a different machine and Operating System. E.g. I am using windows to develop the testcases, but need to upload them to my contest management system which is running Linux.

**Comment by MokshitSurana** [comment]
Ah got it! I'm not much of a pro in this but if you need any help just hmu

**Comment by benwoo1110** [comment]
If you think you can implement, feel free to PR :)
